name: Tests with NornicDB on PHP 8.5

on:
  pull_request:
    branches: [ master ]

jobs:
  nornicdb-tests:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    name: "Running Integration tests for PHP on NornicDB"

    services:
      nornicdb:
        image: timothyswt/nornicdb-amd64-cpu
        ports:
          - 7687:7687
          - 7474:7474
        options: >-
          --health-cmd "wget http://localhost:7474 || exit 1"

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: mbstring, sockets
          coverage: xdebug
          ini-values: max_execution_time=0

      - name: Install dependencies
        run: composer install --no-progress

      - name: Test with phpunit
        run: vendor/bin/phpunit --configuration phpunit.xml --testsuite "NornicDB"
